# See the dedicated "version" documentation section.
version: "2"
linters:
  settings:
    staticcheck:
      checks:
        - all
        - '-ST1003' # disable the rule ST1003
        - '-ST1000' # disable the rule ST1003
