// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID           int32
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	Organiser    pgtype.Text
	IsOnline     bool
	LocationName pgtype.Text
	StartTime    pgtype.Timestamp
	EndTime      pgtype.Timestamp
	Details      pgtype.Text
}

type User struct {
	ID          int32
	FirebaseUid string
	CreatedAt   pgtype.Timestamp
	UserName    string
	Email       string
}
