// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEventById = `-- name: GetEventById :one
SELECT
    e.id, e.created_at, e.updated_at, e.organiser, e.is_online, e.location_name, e.start_time, e.end_time, e.details, e.event_name,
    (er.user_id IS NOT NULL)::boolean AS is_registered
FROM events AS e
LEFT JOIN event_registrations AS er
    ON e.id = er.event_id AND er.user_uid = $2
WHERE e.id = $1
`

type GetEventByIdParams struct {
	ID      int32
	UserUid string
}

type GetEventByIdRow struct {
	ID           int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Organiser    pgtype.Text
	IsOnline     bool
	LocationName pgtype.Text
	StartTime    pgtype.Timestamptz
	EndTime      pgtype.Timestamptz
	Details      pgtype.Text
	EventName    string
	IsRegistered bool
}

func (q *Queries) GetEventById(ctx context.Context, arg GetEventByIdParams) (GetEventByIdRow, error) {
	row := q.db.QueryRow(ctx, getEventById, arg.ID, arg.UserUid)
	var i GetEventByIdRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Organiser,
		&i.IsOnline,
		&i.LocationName,
		&i.StartTime,
		&i.EndTime,
		&i.Details,
		&i.EventName,
		&i.IsRegistered,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT
    id,
    organiser,
    is_online,
    location_name,
    start_time,
    end_time,
    event_name
FROM events
`

type ListEventsRow struct {
	ID           int32
	Organiser    pgtype.Text
	IsOnline     bool
	LocationName pgtype.Text
	StartTime    pgtype.Timestamptz
	EndTime      pgtype.Timestamptz
	EventName    string
}

func (q *Queries) ListEvents(ctx context.Context) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsRow
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Organiser,
			&i.IsOnline,
			&i.LocationName,
			&i.StartTime,
			&i.EndTime,
			&i.EventName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsWithUserRegistration = `-- name: ListEventsWithUserRegistration :many
SELECT
    e.id,
    e.organiser,
    e.is_online,
    e.location_name,
    e.start_time,
    e.end_time,
    e.event_name,
    (er.user_id IS NOT NULL)::boolean AS is_registered
FROM events AS e
LEFT JOIN event_registrations AS er
    ON e.id = er.event_id AND er.user_uid = $1
`

type ListEventsWithUserRegistrationRow struct {
	ID           int32
	Organiser    pgtype.Text
	IsOnline     bool
	LocationName pgtype.Text
	StartTime    pgtype.Timestamptz
	EndTime      pgtype.Timestamptz
	EventName    string
	IsRegistered bool
}

func (q *Queries) ListEventsWithUserRegistration(ctx context.Context, userUid string) ([]ListEventsWithUserRegistrationRow, error) {
	rows, err := q.db.Query(ctx, listEventsWithUserRegistration, userUid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsWithUserRegistrationRow
	for rows.Next() {
		var i ListEventsWithUserRegistrationRow
		if err := rows.Scan(
			&i.ID,
			&i.Organiser,
			&i.IsOnline,
			&i.LocationName,
			&i.StartTime,
			&i.EndTime,
			&i.EventName,
			&i.IsRegistered,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerEvent = `-- name: RegisterEvent :one
INSERT INTO event_registrations (user_uid, event_id)
VALUES ($1, $2)
RETURNING id, event_id, user_uid, registration_date
`

type RegisterEventParams struct {
	UserUid string
	EventID int32
}

func (q *Queries) RegisterEvent(ctx context.Context, arg RegisterEventParams) (EventRegistration, error) {
	row := q.db.QueryRow(ctx, registerEvent, arg.UserUid, arg.EventID)
	var i EventRegistration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserUid,
		&i.RegistrationDate,
	)
	return i, err
}
