// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    event_name,
    organiser,
    is_online,
    location_name,
    start_time,
    end_time,
    registration_link,
    details
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, created_at, updated_at, organiser, is_online, location_name, start_time, end_time, details, event_name, state, registration_link
`

type CreateEventParams struct {
	EventName        string
	Organiser        pgtype.Text
	IsOnline         bool
	LocationName     pgtype.Text
	StartTime        pgtype.Timestamptz
	EndTime          pgtype.Timestamptz
	RegistrationLink pgtype.Text
	Details          pgtype.Text
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.EventName,
		arg.Organiser,
		arg.IsOnline,
		arg.LocationName,
		arg.StartTime,
		arg.EndTime,
		arg.RegistrationLink,
		arg.Details,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Organiser,
		&i.IsOnline,
		&i.LocationName,
		&i.StartTime,
		&i.EndTime,
		&i.Details,
		&i.EventName,
		&i.State,
		&i.RegistrationLink,
	)
	return i, err
}

const getEventById = `-- name: GetEventById :one
SELECT
    id, created_at, updated_at, organiser, is_online, location_name, start_time, end_time, details, event_name, state, registration_link
FROM events
WHERE id = $1
`

// Admin Queries
func (q *Queries) GetEventById(ctx context.Context, id int32) (Event, error) {
	row := q.db.QueryRow(ctx, getEventById, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Organiser,
		&i.IsOnline,
		&i.LocationName,
		&i.StartTime,
		&i.EndTime,
		&i.Details,
		&i.EventName,
		&i.State,
		&i.RegistrationLink,
	)
	return i, err
}

const getEventByIdAndUid = `-- name: GetEventByIdAndUid :one
SELECT
    e.id, e.created_at, e.updated_at, e.organiser, e.is_online, e.location_name, e.start_time, e.end_time, e.details, e.event_name, e.state, e.registration_link,
    (er.user_uid IS NOT NULL)::boolean AS is_registered
FROM events AS e
LEFT JOIN event_registrations AS er
    ON e.id = er.event_id AND er.user_uid = $2
WHERE e.id = $1
`

type GetEventByIdAndUidParams struct {
	ID      int32
	UserUid string
}

type GetEventByIdAndUidRow struct {
	ID               int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Organiser        pgtype.Text
	IsOnline         bool
	LocationName     pgtype.Text
	StartTime        pgtype.Timestamptz
	EndTime          pgtype.Timestamptz
	Details          pgtype.Text
	EventName        string
	State            NullStates
	RegistrationLink pgtype.Text
	IsRegistered     bool
}

func (q *Queries) GetEventByIdAndUid(ctx context.Context, arg GetEventByIdAndUidParams) (GetEventByIdAndUidRow, error) {
	row := q.db.QueryRow(ctx, getEventByIdAndUid, arg.ID, arg.UserUid)
	var i GetEventByIdAndUidRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Organiser,
		&i.IsOnline,
		&i.LocationName,
		&i.StartTime,
		&i.EndTime,
		&i.Details,
		&i.EventName,
		&i.State,
		&i.RegistrationLink,
		&i.IsRegistered,
	)
	return i, err
}

const getEventRegisteredUsers = `-- name: GetEventRegisteredUsers :many
SELECT u.id, u.firebase_uid, u.created_at, u.display_name, u.email, u.updated_at, u.is_admin, u.state, u.age
FROM event_registrations AS er
INNER JOIN users AS u
    ON er.user_uid = u.firebase_uid
WHERE er.event_id = $1
`

func (q *Queries) GetEventRegisteredUsers(ctx context.Context, eventID int32) ([]User, error) {
	rows, err := q.db.Query(ctx, getEventRegisteredUsers, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirebaseUid,
			&i.CreatedAt,
			&i.DisplayName,
			&i.Email,
			&i.UpdatedAt,
			&i.IsAdmin,
			&i.State,
			&i.Age,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT
    id,
    organiser,
    is_online,
    location_name,
    start_time,
    end_time,
    event_name
FROM events
ORDER BY start_time
`

type ListEventsRow struct {
	ID           int32
	Organiser    pgtype.Text
	IsOnline     bool
	LocationName pgtype.Text
	StartTime    pgtype.Timestamptz
	EndTime      pgtype.Timestamptz
	EventName    string
}

func (q *Queries) ListEvents(ctx context.Context) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsRow
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Organiser,
			&i.IsOnline,
			&i.LocationName,
			&i.StartTime,
			&i.EndTime,
			&i.EventName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsAdmin = `-- name: ListEventsAdmin :many
SELECT
    e.id,
    e.organiser,
    e.is_online,
    e.location_name,
    e.start_time,
    e.end_time,
    e.details,
    e.event_name,
    COUNT(er.user_uid) AS user_count
FROM events AS e
LEFT JOIN event_registrations AS er
    ON e.id = er.event_id
GROUP BY e.id
ORDER BY e.start_time
`

type ListEventsAdminRow struct {
	ID           int32
	Organiser    pgtype.Text
	IsOnline     bool
	LocationName pgtype.Text
	StartTime    pgtype.Timestamptz
	EndTime      pgtype.Timestamptz
	Details      pgtype.Text
	EventName    string
	UserCount    int64
}

func (q *Queries) ListEventsAdmin(ctx context.Context) ([]ListEventsAdminRow, error) {
	rows, err := q.db.Query(ctx, listEventsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsAdminRow
	for rows.Next() {
		var i ListEventsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Organiser,
			&i.IsOnline,
			&i.LocationName,
			&i.StartTime,
			&i.EndTime,
			&i.Details,
			&i.EventName,
			&i.UserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsUser = `-- name: ListEventsUser :many
SELECT
    e.id,
    e.organiser,
    e.is_online,
    e.location_name,
    e.state,
    e.start_time,
    e.end_time,
    e.event_name,
    (er.user_uid IS NOT NULL)::boolean AS is_registered
FROM events AS e
LEFT JOIN event_registrations AS er
    ON e.id = er.event_id AND er.user_uid = $1
WHERE
    e.start_time >= NOW()
ORDER BY e.start_time
`

type ListEventsUserRow struct {
	ID           int32
	Organiser    pgtype.Text
	IsOnline     bool
	LocationName pgtype.Text
	State        NullStates
	StartTime    pgtype.Timestamptz
	EndTime      pgtype.Timestamptz
	EventName    string
	IsRegistered bool
}

func (q *Queries) ListEventsUser(ctx context.Context, userUid string) ([]ListEventsUserRow, error) {
	rows, err := q.db.Query(ctx, listEventsUser, userUid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsUserRow
	for rows.Next() {
		var i ListEventsUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Organiser,
			&i.IsOnline,
			&i.LocationName,
			&i.State,
			&i.StartTime,
			&i.EndTime,
			&i.EventName,
			&i.IsRegistered,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerEvent = `-- name: RegisterEvent :one
INSERT INTO event_registrations (user_uid, event_id)
VALUES ($1, $2)
RETURNING id, event_id, user_uid, registration_date
`

type RegisterEventParams struct {
	UserUid string
	EventID int32
}

func (q *Queries) RegisterEvent(ctx context.Context, arg RegisterEventParams) (EventRegistration, error) {
	row := q.db.QueryRow(ctx, registerEvent, arg.UserUid, arg.EventID)
	var i EventRegistration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserUid,
		&i.RegistrationDate,
	)
	return i, err
}
