// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal.sql

package sqlc

import (
	"context"
)

const createJournal = `-- name: CreateJournal :one
INSERT INTO journals (
    user_uid,
    title,
    journal_content
) VALUES ($1, $2, $3)
RETURNING id, user_uid, created_at, updated_at, title, journal_content
`

type CreateJournalParams struct {
	UserUid        string
	Title          string
	JournalContent string
}

func (q *Queries) CreateJournal(ctx context.Context, arg CreateJournalParams) (Journal, error) {
	row := q.db.QueryRow(ctx, createJournal, arg.UserUid, arg.Title, arg.JournalContent)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.UserUid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.JournalContent,
	)
	return i, err
}

const getJournal = `-- name: GetJournal :one
SELECT id, user_uid, created_at, updated_at, title, journal_content FROM journals
WHERE id = $1
`

func (q *Queries) GetJournal(ctx context.Context, id int32) (Journal, error) {
	row := q.db.QueryRow(ctx, getJournal, id)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.UserUid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.JournalContent,
	)
	return i, err
}

const listJournals = `-- name: ListJournals :many
SELECT
    title,
    journal_content
FROM journals
WHERE user_uid = $1
ORDER BY updated_at
`

type ListJournalsRow struct {
	Title          string
	JournalContent string
}

func (q *Queries) ListJournals(ctx context.Context, userUid string) ([]ListJournalsRow, error) {
	rows, err := q.db.Query(ctx, listJournals, userUid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJournalsRow
	for rows.Next() {
		var i ListJournalsRow
		if err := rows.Scan(&i.Title, &i.JournalContent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
