// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJournal = `-- name: CreateJournal :one
INSERT INTO journals (
    user_uid,
    title,
    journal_content
) VALUES ($1, $2, $3)
RETURNING id, user_uid, created_at, updated_at, title, journal_content
`

type CreateJournalParams struct {
	UserUid        string
	Title          string
	JournalContent string
}

func (q *Queries) CreateJournal(ctx context.Context, arg CreateJournalParams) (Journal, error) {
	row := q.db.QueryRow(ctx, createJournal, arg.UserUid, arg.Title, arg.JournalContent)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.UserUid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.JournalContent,
	)
	return i, err
}

const getJournal = `-- name: GetJournal :one
SELECT id, user_uid, created_at, updated_at, title, journal_content FROM journals
WHERE id = $1 AND user_uid = $2
`

type GetJournalParams struct {
	ID      int32
	UserUid string
}

func (q *Queries) GetJournal(ctx context.Context, arg GetJournalParams) (Journal, error) {
	row := q.db.QueryRow(ctx, getJournal, arg.ID, arg.UserUid)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.UserUid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.JournalContent,
	)
	return i, err
}

const listJournals = `-- name: ListJournals :many
SELECT
    id,
    created_at,
    updated_at,
    title
FROM journals
WHERE user_uid = $1
ORDER BY updated_at DESC
`

type ListJournalsRow struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Title     string
}

func (q *Queries) ListJournals(ctx context.Context, userUid string) ([]ListJournalsRow, error) {
	rows, err := q.db.Query(ctx, listJournals, userUid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJournalsRow
	for rows.Next() {
		var i ListJournalsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
