// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID           int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Organiser    pgtype.Text
	IsOnline     bool
	LocationName pgtype.Text
	StartTime    pgtype.Timestamptz
	EndTime      pgtype.Timestamptz
	Details      pgtype.Text
	EventName    string
}

type EventRegistration struct {
	ID               int32
	EventID          int32
	UserUid          string
	RegistrationDate pgtype.Timestamp
}

type User struct {
	ID          int32
	FirebaseUid string
	CreatedAt   pgtype.Timestamptz
	DisplayName string
	Email       string
	UpdatedAt   pgtype.Timestamptz
	IsAdmin     bool
}
