// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (firebase_uid, user_name, email)
VALUES ($1, $2, $3)
RETURNING id, firebase_uid, created_at, user_name, email, updated_at
`

type CreateUserParams struct {
	FirebaseUid string
	UserName    string
	Email       string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.FirebaseUid, arg.UserName, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.CreatedAt,
		&i.UserName,
		&i.Email,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, firebase_uid, created_at, user_name, email, updated_at FROM users
WHERE id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.CreatedAt,
		&i.UserName,
		&i.Email,
		&i.UpdatedAt,
	)
	return i, err
}
