// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (firebase_uid, display_name, email)
VALUES ($1, $2, $3)
RETURNING id, firebase_uid, created_at, display_name, email, updated_at, is_admin
`

type CreateUserParams struct {
	FirebaseUid string
	DisplayName string
	Email       string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.FirebaseUid, arg.DisplayName, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Email,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const createUserIfAbsent = `-- name: CreateUserIfAbsent :one
INSERT INTO users (firebase_uid, display_name, email)
VALUES ($1, $2, $3)
ON CONFLICT (firebase_uid) DO NOTHING
RETURNING id, firebase_uid, created_at, display_name, email, updated_at, is_admin
`

type CreateUserIfAbsentParams struct {
	FirebaseUid string
	DisplayName string
	Email       string
}

func (q *Queries) CreateUserIfAbsent(ctx context.Context, arg CreateUserIfAbsentParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserIfAbsent, arg.FirebaseUid, arg.DisplayName, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Email,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByUid = `-- name: GetUserByUid :one
SELECT id, firebase_uid, created_at, display_name, email, updated_at, is_admin FROM users
WHERE firebase_uid = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetUserByUid(ctx context.Context, firebaseUid string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUid, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Email,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}
