// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (firebase_uid, display_name, email, state, date_of_birth)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (firebase_uid) DO NOTHING
RETURNING id, firebase_uid, created_at, display_name, email, updated_at, is_admin, state, date_of_birth
`

type CreateUserParams struct {
	FirebaseUid string
	DisplayName string
	Email       string
	State       NullStates
	DateOfBirth pgtype.Date
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirebaseUid,
		arg.DisplayName,
		arg.Email,
		arg.State,
		arg.DateOfBirth,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Email,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.State,
		&i.DateOfBirth,
	)
	return i, err
}

const getUserByUid = `-- name: GetUserByUid :one
SELECT id, firebase_uid, created_at, display_name, email, updated_at, is_admin, state, date_of_birth FROM users
WHERE firebase_uid = $1
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetUserByUid(ctx context.Context, firebaseUid string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUid, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Email,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.State,
		&i.DateOfBirth,
	)
	return i, err
}
